/*SEQUENCE ESTADO*/
CREATE SEQUENCE seq_estado START 1 INCREMENT 1 MINVALUE 1 OWNED BY tb_estado.id;

/*SEQUENCE CIDADE*/
CREATE SEQUENCE seq_cidade START 1 INCREMENT 1 MINVALUE 1 OWNED BY tb_cidade.id;

/*SEQUENCE PESSOA*/
CREATE SEQUENCE seq_pessoa START 1 INCREMENT 1 MINVALUE 1 OWNED BY tb_pessoa.id;

/*SEQUENCE ENDERECO*/
CREATE SEQUENCE seq_endereco START 1 INCREMENT 1 MINVALUE 1 OWNED BY tb_endereco.id;

/*SEQUENCE BANCO*/
CREATE SEQUENCE seq_banco START 1 INCREMENT 1 MINVALUE 1 OWNED BY tb_banco.id;

/*SEQUENCE CONTA*/
CREATE SEQUENCE seq_conta START 1 INCREMENT 1 MINVALUE 1 OWNED BY tb_conta.id;

/*SEQUENCE HISTORICO FINANCEIRO*/
CREATE SEQUENCE seq_historico_financeiro START 1 INCREMENT 1 MINVALUE 1 OWNED BY tb_historico_financeiro.id;

/*SEQUENCE MOVIMENTO AVULSO*/
CREATE SEQUENCE seq_movimento_avulso START 1 INCREMENT 1 MINVALUE 1 OWNED BY tb_movimento_avulso.id;

/*SEQUENCE CONTA PAGAR*/
CREATE SEQUENCE seq_conta_pagar START 1 INCREMENT 1 MINVALUE 1 OWNED BY tb_conta_pagar.id;

/*SEQUENCE CONTA RECEBER*/
CREATE SEQUENCE seq_conta_receber START 1 INCREMENT 1 MINVALUE 1 OWNED BY tb_conta_receber.id;

/*SEQUENCE GRUPO USUARIO*/
CREATE SEQUENCE seq_grupo_usuario START 1 INCREMENT 1 MINVALUE 1 OWNED BY tb_grupo_usuario.id;

/*SEQUENCE USUARIO*/
CREATE SEQUENCE seq_usuario START 1 INCREMENT 1 MINVALUE 1 OWNED BY tb_usuario.id;